### PR TITLE
Deliver Dancer Via Apache/CGI

### PR DESCRIPTION
**Pull request by goehle**
Changed things so that the dancer components of webwork3 are served via apache using cgi.

In order for this to work you need to enable the apache module fcgi (or fcgid) on your machine.  (I had to do 
sudo apt-get install libapache2-mod-fcgid).  You also need Plack::Runner (I did apt-get install libplack-perl).  

Note:  I'm still having trouble getting the manager to work, so there may be something incomplete here. 

Pros:  
- Dancer doesn't have to be started on its own.  This means that we don't have to worry about how to deploy dancer as a service on all the different distributions.  
- Dancer doesn't have to be run manually, in fact you can change something in dancer, hit refresh and it uses the new code. 

Cons: 
- It seems a little slower.  
- Its a little harder to get debug information since its not spewing onto the screen.  (Need to have a debug log file.)

### CODE REVIEW

**Comment by pstaabp** [comment]
I don’t understand why you need this.  Dancer can handle all of this and our production machine has been running everything fine.   Also, I think long term, we can ditch using Apache.  

Again, we need to work on a script to start dancer automatically.  I think this is a big thing to do before the May code camp, but I’ll make it a priority. 

Maybe we should talk this week about deploying webwork3.  I should have also pointed out that I have successfully been using a service called ubic for starting and restarting dancer.  I put up directions on https://github.com/openwebwork/webwork2/wiki/Deploy-WeBWorK3 

I should have mentioned that, but I’ve been running all the dancer stuff on my laptop with no problems without that.

**Comment by goehle** [comment]
This doesn't change any of that.  It just changes how the http requests get
to dancer.  Installing services is a pain, because they are very distro
dependent.  That script will need lots of testing on half a dozen server
setups and will be a big project.  This runs off apache with standard
modules and will require no additional configuration on the part of
administrators.  The harder it is to get webwork 3 running the more likely
it will be that someone who wants to use it will make a mistake, click on
the link, and be disjointed.

The nice thing about this approach is that it doesn't prevent you from
serving requests directly from dancer either.  You can still use dancer's
built in server; just add the proxy lines back in (now that I think about
it it, they should be added back in, and commented with a note).

(The changes to app.pl just make it easier for app.pl to get the WeBWorK
libraries and will help in general.)

Geoff.

**Comment by pstaabp** [comment]
When Mike and I both deployed this on our servers we found that using the ProxyPass was the easier to get thing up and running, but we can consider other options.

About the services, I’m running ubic, a perl service platform and should be very compatible with the rest of webwork.  I have yet to get it started when the computer boots up, but that’s because I haven’t looked into it yet.

**Comment by goehle** [comment]
ProxyPass is simple on the apache side, but requires us to make sure that
dancer is running or things look broken.  I barely remember to start
dancer, and I'm involved with all of this.  This approach is about 5 lines
of code, added to an existing WeBWorK file and requiring standard apache
modules and perl packages, it completely solves the issue of making sure
dancer is running in a distribution independent way, and it does so in a
way that is compatible with running off dancer directly.

I'm just trying to be practical.   A script which sets up dancer as a
service would be nice, and may even be more robust than this.  Certainly
when we are at a point where we are considering phasing out
ContentGenerator, its something we will want to have.   But you said
yourself that you weren't sure you could get it done by May.  As long as we
have ContentGenerator around, which will be for a while, we will have an
apache server available to us.  That lets us solve deployment now in a
reasonable way.  I'm sure there will be bugs, but I really want to get a
solution that doesn't  require extra work on the part of admins.

(Keep in mind, its mod_perl that Jason and I were having so much trouble
with before, and that we want to move away from.  Apache in general is
still the industry standard for webservers, even if its not the newest and
shiniest )
Geoff.

**Comment by pstaabp** [comment]
I think I see your point about making something robust.  We can move in the direction you’re suggesting. I’ll pull in these changes and test on my side as well. 

A thought about making sure that dancer is running could be handled in our webwork-apache2.config file (to start/restart) dancer when we start/restart apache.  That could be as simple a line or two of code.  I haven’t looked into that, but can.

**Comment by goehle** [comment]
I speeded things up a little bit by having apache serve static files directly.  

Also, I forgot to mention that since things are being served by apache in the new configuration in addition to installing  libapache2-mod-fcgid and libplack-perl, you will need to make the public directory in webwork3 have the wwdata group (or some other webserver accessible group).  

At the end of the day multiple deployment options are a good thing, I think. The method I am using is the very first listed here: http://search.cpan.org/~yanick/Dancer-1.3121/lib/Dancer/Deployment.pod.  However, reasonable people will differ.  For example, that documentation has this to say about running off of dancer directly "This option can be useful for small personal web apps or internal apps, but if you want to make your app available to the world, it probably won't suit you" (in the Running stand-alone section).  So clearly that author is biased to one direction.  Having both available can't hurt, and then the default will be whichever is the best at getting ww3 to new users.

**Pull request merged**
